spring:
  application:
    name:  service1
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka1:8071/eureka/,http://eureka2:8072/eureka/
---
server:
  port: 8090
spring:
  config:
    activate:
      on-profile: instance1
---
server:
  port: 8091
spring:
  config:
    activate:
      on-profile: instance2
---
server:
  port: 8092
spring:
  config:
    activate:
      on-profile: instance3